INSERT INTO menu_descriptions (item_id, lang_code, title, description) VALUES
(1, 'en', 'Spaghetti with Two Fried Chicken Pieces', 'Banana ketchup, ground beef or hotdogs, spaghetti noodles, garlic, seasoned fried chicken'),
(1, 'fr', 'Spaghetti avec deux morceaux de poulet frit', 'Ketchup à la banane, bœuf haché ou hot-dogs, nouilles spaghetti, ail, poulet frit assaisonné'),
(1, 'tl', 'Spaghetti na may Dalawang Pritong Manok', 'Saging na ketchup, giniling na karne o hotdog, spaghetti noodles, bawang, tinimplahang pritong manok'),
(2, 'en', 'Palabok with One Pork BBQ Skewer', 'Rice noodles, shrimp sauce (stock and annatto), crushed chicharron, boiled egg'),
(2, 'fr', 'Palabok avec une brochette de porc BBQ', 'Nouilles de riz, sauce aux crevettes (bouillon et annatto), chicharron écrasé, œuf dur'),
(2, 'tl', 'Palabok na may Isang BBQ na Baboy', 'Bihon, shrimp sauce mula sa sabaw at annatto, durug na chicharon, nilagang itlog'),
(3, 'en', 'Pancit with Fried Chicken & Pork BBQ Skewer', 'Bihon or canton noodles, soy sauce, vegetables, fried chicken, pork bbq marinade'),
(3, 'fr', 'Pancit avec poulet frit et brochette de porc BBQ', 'Nouilles bihon ou canton, sauce soja, légumes, poulet frit, marinade BBQ au porc'),
(3, 'tl', 'Pancit na may Manok at BBQ na Baboy', 'Bihon o canton noodles, toyo, gulay, pritong manok, BBQ marinade ng baboy'),
(4, 'en', 'Rice with One Fried Chicken & Fish Fillet','White rice, seasoned fried chicken, breaded fish fillet, lemon or calamansi for garnish'),
(4, 'fr', 'Riz avec un morceau de poulet frit et filet de poisson','riz blanc, poulet frit assaisonné, filet de poisson pané, citron ou calamansi pour la garniture'),
(4, 'tl', 'Kanin na may Isang Fried Chicken at Fish Fillet','puting kanin, tinimplahang fried chicken, tinapay na fish fillet, lemon o calamansi para sa palamuti'),
(5, 'en', 'Rice with Two Fried Chicken & Pork BBQ Skewer','White rice, seasoned fried chicken, pork BBQ marinade (banana ketchup, soy sauce, brown sugar, garlic)'),
(5, 'fr', 'Riz avec deux morceaux de poulet frit et une brochette de porc BBQ','riz blanc, poulet frit assaisonné, marinade de porc BBQ (ketchup banane, sauce soja, cassonade, ail)'),
(5, 'tl', 'Kanin na may Dalawang Fried Chicken at Pork BBQ Skewer','puting kanin, tinimplahang fried chicken, pork BBQ marinade (banana ketchup, toyo, brown sugar, bawang)'),
(6, 'en', 'Rice with Fish Fillet & Chicken BBQ','white rice, chicken BBQ (marinated in calamansi, soy sauce, brown sugar), breaded fish fillet, dipping sauce'),
(6, 'fr', 'Riz avec filet de poisson et poulet BBQ','riz blanc, poulet BBQ (mariné dans calamansi, sauce soja, cassonade), filet de poisson pané, sauce trempette'),
(6, 'tl', 'Kanin na may Fish Fillet at Chicken BBQ','puting kanin, chicken BBQ (minarinade sa calamansi, toyo, brown sugar), tinapay na fish fillet, sawsawan'),
(7, 'en', 'Rice with Pork BBQ Skewer & Chicken BBQ','White rice, pork BBQ, chicken BBQ, marinade (soy sauce, vinegar, garlic, brown sugar), achuete oil'),
(7, 'fr', 'Riz avec brochette de porc BBQ et poulet BBQ','riz blanc, porc BBQ, poulet BBQ, marinade (sauce soja, vinaigre, ail, cassonade), huile d''achuete'),
(7, 'tl', 'Kanin na may Pork BBQ Skewer at Chicken BBQ','puting kanin, pork BBQ, chicken BBQ, marinade (toyo, suka, bawang, brown sugar), achuete oil'),
(8, 'en', 'Rice with Chicken BBQ','white rice, chicken BBQ (calamansi, soy sauce, brown sugar, garlic), annatto oil for glaze'),
(8, 'fr', 'Riz avec poulet BBQ','riz blanc, poulet BBQ (calamansi, sauce soja, cassonade, ail), huile de rocou pour le glaçage'),
(8, 'tl', 'Kanin na may Chicken BBQ','puting kanin, chicken BBQ (calamansi, toyo, brown sugar, bawang), annatto oil para sa glaze'),
(9,'en','Seafood Boil',''),
(9,'fr','Fruits de Mer Bouillis',''),
(9,'tl','Nilagang Lamang-Dagat',''),
(10,'en','LOVE Platter',''),
(10,'fr','Plat LOVE',''),
(10,'tl','LOVE Platter',''),
(11,'en','Tapsilog','beef, fried egg, garlic fried rice'),
(11,'fr','Tapsilog','bœuf, œuf frit, riz frit à l''ail'),
(11,'tl','Tapsilog','karne ng baka, pritong itlog, sinangag'),
(12,'en','Tosilog','pork, fried egg, garlic fried rice'),
(12,'fr','Tosilog','porc, œuf frit, riz frit à l''ail'),
(12,'tl','Tosilog','karne ng baboy, pritong itlog, sinangag'),
(13,'en','Spamsilog','spam, fried egg, garlic fried rice'),
(13,'fr','Spamsilog','spam, œuf frit, riz frit à l''ail'),
(13,'tl','Spamsilog','spam, pritong itlog, sinangag'),
(14,'en','Bangsilog','fish, fried egg, garlic fried rice'),
(14,'fr','Bangsilog','poisson, œuf frit, riz frit à l''ail'),
(14,'tl','Bangsilog','isda, pritong itlog, sinangag'),
(15,'en','Cornsilog','corned beef, fried egg, garlic fried rice'),
(15,'fr','Cornsilog','corned beef, œuf frit, riz frit à l''ail'),
(15,'tl','Cornsilog','corned beef, pritong itlog, sinangag'),
(16,'en','Calamari',''),
(16,'fr','Calamars',''),
(16,'tl','Calamari',''),
(17,'en','Shanghai (10 pcs.)',''),
(17,'fr','Shanghai (10 pièces)',''),
(17,'tl','Shanghai (10 piraso)',''),
(18,'en','Siomai',''),
(18,'fr','Siomai',''),
(18,'tl','Siomai',''),
(19,'en','Tofu Veggies',''),
(19,'fr','Légumes au Tofu',''),
(19,'tl','Tofu at Gulay',''),
(20,'en','Stirfry Veggies',''),
(20,'fr','Légumes Sautés',''),
(20,'tl','Stirfry na Gulay',''),
(21,'en','Pork Sinigang','pork sour and savory soup'),
(21,'fr','Sinigang de Porc','soupe de porc aigre et salée'),
(21,'tl','Sinigang na Baboy','maasim at malinamnam na sabaw ng baboy'),
(22,'en','Shrimp Sinigang','shrimp sour and savory soup'),
(22,'fr','Sinigang de Crevettes','soupe de crevettes aigre et salée'),
(22,'tl','Sinigang na Hipon','maasim at malinamnam na sabaw ng hipon'),
(23,'en','Balbacua','beef stew'),
(23,'fr','Balbacua','ragoût de bœuf'),
(23,'tl','Balbacua','nilagang baka'),
(24,'en','Bulalo','beef marrow and shanks soup'),
(24,'fr','Bulalo','moelle de bœuf et soupe de jarrets'),
(24,'tl','Bulalo','sabaw ng buto at binti ng baka'),
(25,'en','Mami','wheat flour noodles soup'),
(25,'fr','Mami','soupe de nouilles de blé'),
(25,'tl','Mami','sabaw ng pansit na gawa sa harina ng trigo'),
(26,'en','Miki','egg noodles soup'),
(26,'fr','Miki','soupe de nouilles aux œufs'),
(26,'tl','Miki','sabaw ng pansit na may itlog'),
(27,'en','Spaghetti',''),
(27,'fr','Spaghetti',''),
(27,'tl','Spaghetti',''),
(28,'en','Palabok','starchy noodles'),
(28,'fr','Palabok','nouilles féculentes'),
(28,'tl','Palabok','malagkit na pansit'),
(29,'en','Pancit Bihon','rice vermicelli fried nooodles, vegetables, meat'),
(29,'fr','Pancit Bihon','nouilles de riz vermicelles frites, légumes, viande'),
(29,'tl','Pancit Bihon','pritong bihon, gulay, karne'),
(30,'en','Pancit Canton','thick egg noodle stir fried'),
(30,'fr','Pancit Canton','nouilles épaisses aux œufs sautées'),
(30,'tl','Pancit Canton','makapal na pansit canton na stir-fried'),
(31,'en','Pancit Bam-I','rice and wheat stir fried noodles'),
(31,'fr','Pancit Bam-I','nouilles de riz et de blé sautées'),
(31,'tl','Pancit Bam-I','pritong pansit na gawa sa bigas at trigo'),
(32,'en','Chicken Wings',''),
(32,'fr','Ailes de poulet',''),
(32,'tl','Chicken Wings',''),
(33,'en','Baby Back Ribs',''),
(33,'fr','Côtes levées de porc',''),
(33,'tl','Baby Back Ribs',''),
(34,'en','Dinakdakan','grilled pork head cheese, red onions, calamansi juice'),
(34,'fr','Dinakdakan','fromage de tête de porc grillé, oignons rouges, jus de calamansi'),
(34,'tl','Dinakdakan','inihaw na ulo ng baboy, pulang sibuyas, katas ng calamansi'),
(35,'en','Sisig','grilled pork jowl, pork belly, onions, chili peppers'),
(35,'fr','Sisig','joue de porc grillée, poitrine de porc, oignons, piments'),
(35,'tl','Sisig','inihaw na pisngi ng baboy, tiyan ng baboy, sibuyas, sili'),
(36,'en','Lechon Kawali','deep fried pork belly'),
(36,'fr','Lechon Kawali','poitrine de porc frite'),
(36,'tl','Lechon Kawali','pritong tiyan ng baboy'),
(37,'en','Dinuguan','pork offal stew, chili, vinegar'),
(37,'fr','Dinuguan','ragoût d''abats de porc, piment, vinaigre'),
(37,'tl','Dinuguan','nilagang lamang-loob ng baboy, sili, suka'),
(38,'en','Beef Steak',''),
(38,'fr','Bifteck',''),
(38,'tl','Beef Steak',''),
(39,'en','Bicol Express','pork cubes, coconut milk, chili peppers, allium stew'),
(39,'fr','Bicol Express','cubes de porc, lait de coco, piments, ragoût d''ailiacées'),
(39,'tl','Bicol Express','cube ng baboy, gata ng niyog, sili, nilagang allium'),
(40,'en','Fish Fillet',''),
(40,'fr','Filet de poisson',''),
(40,'tl','Fish Fillet',''),
(41,'en','Sweet and Sour Fish',''),
(41,'fr','Poisson aigre-doux',''),
(41,'tl','Sweet and Sour Fish',''),
(42,'en','Bucket Shrimp',''),
(42,'fr','Seau de crevettes',''),
(42,'tl','Bucket ng Hipon',''),
(43,'en','Dried Danggit','Dried Fish'),
(43,'fr','Danggit Séché','Poisson séché'),
(43,'tl','Pinatuyong Danggit','Pinatuyong Isda'),
(44,'en','Dried Pusit','Dried Squid'),
(44,'fr','Pusit Séché','Calmar séché'),
(44,'tl','Pinatuyong Pusit','Mga Karagdagang'),
(45,'en','Pork BBQ Skewer',''),
(45,'fr','Brochette de porc BBQ',''),
(45,'tl','Pork BBQ Skewer',''),
(46,'en','Chicken BBQ',''),
(46,'fr','Poulet BBQ',''),
(46,'tl','Chicken BBQ',''),
(47,'en','Fried Chicken (1 pc.)','Less than 10: $3.00 each, More than 10: $2.50 each'),
(47,'fr','Poulet Frit (1 pièce)','Moins de 10: 3,00 $ chacun, Plus de 10: 2,50 $ chacun'),
(47,'tl','Fried Chicken (1 piraso)','Mas mababa sa 10: $3.00 bawat isa, Higit sa 10: $2.50 bawat isa'),
(48,'en','Steam Rice',''),
(48,'fr','Riz Vapeur',''),
(48,'tl','Kanin',''),
(49,'en','Pork Ribs',''),
(49,'fr','Côtes de Porc',''),
(49,'tl','Pork Ribs',''),
(50,'en','Garlic Fried Rice',''),
(50,'fr','Riz Frit à l''Ail',''),
(50,'tl','Sinangag',''),
(51,'en','Bangus (1 whole pc.)','fried whole fish'),
(51,'fr','Bangus (1 pièce entière)','poisson entier frit'),
(51,'tl','Bangus (1 buong piraso)','pritong buong isda'),
(52,'en','Chorizo (4 pcs.)','Filipino style spicy sausage'),
(52,'fr','Chorizo (4 pièces)','Saucisse épicée de style philippin'),
(52,'tl','Chorizo (4 na piraso)','Filipino style na maanghang na longganisa'),
(53,'en','Leche Flan','caramel custard'),
(53,'fr','Leche Flan','Crème caramel'),
(53,'tl','Leche Flan','caramel Custard'),
(54,'en','Buko Pandan','shredded young coconut (buko), pandan flavored jelly, sweetened cream'),
(54,'fr','Buko Pandan','jeune noix de coco râpée (buko), gelée aromatisée au pandan, crème sucrée'),
(54,'tl','Buko Pandan','nilaga na buko, pandan flavored jelly, pinatamis na cream'),
(55,'en','Halo-Halo','shaved ice, sweetened fruits, jellies and beans, coconut or evaporated milk'),
(55,'fr','Halo-Halo','glace pilée, fruits confits, gelées et haricots, lait de coco ou lait évaporé'),
(55,'tl','Halo-Halo','nilaga na yelo, pinatamis na prutas, jellies at beans, gata o evaporated milk'),
(56,'en','Coffee Jelly',''),
(56,'fr','Gelée de café',''),
(56,'tl','Coffee Jelly',''),
(57,'en','Ice Cream',''),
(57,'fr','Crème glacée',''),
(57,'tl','Ice Cream',''),
(58,'en','Palamig','tapioca pearls, sweet agar-agar jelly, fruit syrups, sweetened cold flavored water'),
(58,'fr','Palamig','perles de tapioca, gelée d''agar-agar sucrée, sirops de fruits, eau froide aromatisée sucrée'),
(58,'tl','Palamig','tapioca pearls, matamis na agar-agar jelly, fruit syrups, pinatamis na malamig na tubig na may lasa'),
(59,'en','Water Bottle',''),
(59,'fr','Bouteille d''eau',''),
(59,'tl','Water Bottle',''),
(60,'en','Coffee',''),
(60,'fr','Café',''),
(60,'tl','Kape',''),
(61,'en','Soft Drinks',''),
(61,'fr','Boissons gazeuses',''),
(61,'tl','Soft Drinks','');